import os
from dotenv import load_dotenv
from google import genai
from google.genai import types

from services.supabase_client import supabase

load_dotenv()


class AIService:
    SIMILARITY_THRESHOLD = 0.70

    @staticmethod
    def answer_question(role, question, user_id=None):
        role = role.lower()

        local_result = AIService.search_vector_knowledge(question, role)

        if local_result:
            return {
                "source": "vector_database",
                "answer": local_result["content"],
                "matched_title": local_result["title"],
                "similarity": local_result["similarity"],
                "warning": None
            }

        return AIService.llm_fallback(question)

    @staticmethod
    def create_query_embedding(question):
        client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

        result = client.models.embed_content(
            model="gemini-embedding-001",
            contents=question,
            config=types.EmbedContentConfig(
                task_type="RETRIEVAL_QUERY",
                output_dimensionality=768
            )
        )

        return result.embeddings[0].values

    @staticmethod
    def search_vector_knowledge(question, role):
        query_embedding = AIService.create_query_embedding(question)

        response = supabase.rpc(
            "match_ai_knowledge",
            {
                "query_embedding": query_embedding,
                "match_count": 1,
                "role_filter": role
            }
        ).execute()

        if not response.data:
            return None

        best_match = response.data[0]

        if best_match["similarity"] < AIService.SIMILARITY_THRESHOLD:
            return None

        return best_match

    @staticmethod
    def llm_fallback(question):
        try:
            client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=question
            )

            return {
                "source": "gemini_fallback",
                "answer": response.text,
                "warning": (
                    "Warning: This response was generated by Gemini because no reliable "
                    "answer was found in the local vector database. It may contain inaccuracies or hallucinations."
                )
            }

        except Exception as error:
            return {
                "source": "gemini_error",
                "answer": "No local answer was found and Gemini fallback failed.",
                "warning": str(error)
            }